name: Deploy to Heroku & Docker Hub

on:
  push:
    branches:
      - main  # Runs the workflow when you push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to Heroku
      - name: Login to Heroku
        run: echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username=_ --password-stdin registry.heroku.com

      # Build and push Docker image to Heroku
      - name: Build & Push to Heroku
        run: |
          heroku container:push web -a car-price-ml
          heroku container:release web -a car-price-ml

      # Login to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # Build and push Docker image to Docker Hub
      - name: Build & Push to Docker Hub
        run: |
          docker build -t iblanco10/car-price-predictor .
          docker tag iblanco10/car-price-predictor iblanco10/car-price-predictor:latest
          docker push iblanco10/car-price-predictor:latest
